# alpine использует musl, psycopg2-binary собран для glibc;
# для ускорения сборки не стоит компилировать psycopg2 из исходников,
# проще занять больше места образом buster, чем пересобирать библиотеку каждую сборку образа
FROM python:3.7-buster

WORKDIR /app
COPY . .

COPY contrib/wait-for /usr/local/bin/wait-for

ENV DJANGO_SETTINGS_MODULE=gluttony.settings.dev

RUN apt update && apt install -y python3 python3-pip && pip install -r requirements/dev.txt && chmod +x /usr/local/bin/wait-for

ENTRYPOINT ["/usr/local/bin/wait-for", "postgres:5432", "--", "python3", "manage.py"]
CMD ["runserver", "8000"]
