# Generated by Django 2.2.5 on 2019-09-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'аллерген',
                'verbose_name_plural': 'аллергены',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('energy', models.IntegerField(verbose_name='Энергетическая ценность, ккал')),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='Изображение')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Стоимость за порцию, ₽')),
                ('allergens', models.ManyToManyField(blank=True, to='gluttony.Allergen', verbose_name='Аллергены')),
            ],
            options={
                'verbose_name': 'блюдо',
                'verbose_name_plural': 'блюда',
            },
        ),
    ]
